title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: 华扇独臂成仙
twitter_username: jekyllrb
github_username: Huashan258
bilibili_url: https://space.bilibili.com/29663423  # 替换成你的B站ID

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

aux_links:
  "GitHub":
    - "https://github.com/Huashan258"
  "哔哩哔哩":
    - "https://space.bilibili.com/29663423"

# 显示导航链接的图标
aux_links_new_tab: true