title: 华扇
email: 1095832103@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  欢迎来到华扇的小家，朋友。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: 华扇独臂成仙
twitter_username: None
github_username: Huashan258
bilibili_url: https://space.bilibili.com/29663423  # 替换成你的B站ID

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
sidebar:
  title: 华扇独臂成仙
aux_links:
  "GitHub":
    - "https://github.com/Huashan258"
  "哔哩哔哩":
    - "https://space.bilibili.com/29663423"

# 显示导航链接的图标
aux_links_new_tab: true
markdown: kramdown
       kramdown:
         syntax_highlighter: rouge
         input: GFM # 确保使用GitHub Flavored Markdown